### ISSUE TITLE
submitting error for FHO State Change Object Detection 

### ISSUE THREAD

**Issue by takfate** [EGO4D/hands-and-objects#16]
Hello, we have submitted the results for evaluation, but there are some errors.
```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 491, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmp731rinei/compute/challenge_data/challenge_1632/main.py", line 91, in evaluate
    pred_coco = get_coco_detections(predictions, framesubpath2id)
  File "/tmp/tmp731rinei/compute/challenge_data/challenge_1632/main.py", line 29, in get_coco_detections
    x = box["x"]
TypeError: string indices must be integers
```

Also, we have a question: can each image of the prediction result only contain one box prediction?
Could you give me some help?

**Comment by Sid2697** [comment]
cc @fuqichen1998
