### ISSUE TITLE
Meet error when downloading datasets.

### ISSUE THREAD

**Issue by Mr-Bigworth** [EGO4D/hands-and-objects#21]
Traceback (most recent call last):
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/httpsession.py", line 464, in send
    chunked=self._chunked(request.headers),
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server2/anaconda3/envs/mmdet/bin/ego4d", line 8, in <module>
    sys.exit(main())
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/ego4d/cli/cli.py", line 158, in main_cfg
    skip_s3_checks=validated_cfg.skip_s3_checks,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/ego4d/cli/download.py", line 254, in filter_already_downloaded
    unit="file",
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/ego4d/cli/download.py", line 250, in <lambda>
    lambda x: x.s3_object and not already_downloaded(x) and x.s3_exists,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/ego4d/cli/download.py", line 198, in already_downloaded
    skip_s3_checks or download.exists()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/ego4d/cli/download.py", line 68, in exists
    self.s3_object.load()
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/boto3/resources/factory.py", line 564, in do_action
    response = action(self, *args, **kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/client.py", line 944, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 207, in _send_request
    exception,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 361, in _needs_retry
    request_dict=request_dict,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/utils.py", line 1595, in redirect_from_error
    new_region = self.get_bucket_region(bucket, response)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/utils.py", line 1665, in get_bucket_region
    response = self._client.head_bucket(Bucket=bucket)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/client.py", line 944, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 207, in _send_request
    exception,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 361, in _needs_retry
    request_dict=request_dict,
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/retryhandler.py", line 285, in __call__
    attempt_number, response, caught_exception
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/retryhandler.py", line 364, in __call__
    attempt_number, response, caught_exception
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/retryhandler.py", line 248, in __call__
    attempt_number, caught_exception
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/server2/anaconda3/envs/mmdet/lib/python3.7/site-packages/botocore/httpsession.py", line 495, in send
    error=e, request=request, endpoint_url=request.url
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://ego4d-iiith.s3.ap-south-1.amazonaws.com/".

**Comment by Mr-Bigworth** [comment]
Hello,

'SSLError' ocurred when I ran the command 'ego4d --output_directory="~/ego4d_data_FHO" --datasets full_scale --benchmarks FHO' to download clips.

Could you tell me how to solve it?
